/**
 * AI Trainer Tools Definition
 *
 * 도메인별 도구 정의를 조합하는 진입점.
 */

import type { AIToolName } from '@/lib/types/fitness';
import type { AIToolDefinition } from './tools/types';

export type { AIToolDefinition } from './tools/types';

export {
  GET_USER_BASIC_INFO,
  GET_USER_MILITARY_INFO,
  GET_USER_BODY_METRICS,
  GET_LATEST_INBODY,
  GET_INBODY_HISTORY,
  GET_FITNESS_PROFILE,
  UPDATE_FITNESS_PROFILE,
  GET_DIETARY_PROFILE,
  UPDATE_DIETARY_PROFILE,
  CALCULATE_DAILY_NEEDS,
  REQUEST_USER_INPUT,
  CONFIRM_PROFILE_DATA,
} from './tools/profile-tools';

export {
  GET_CURRENT_ROUTINE,
  ADD_EXERCISE_TO_WORKOUT,
  REMOVE_EXERCISE_FROM_WORKOUT,
  REORDER_WORKOUT_EXERCISES,
  UPDATE_EXERCISE_SETS,
  SAVE_ROUTINE_DRAFT,
  GENERATE_ROUTINE_PREVIEW,
  APPLY_ROUTINE,
} from './tools/routine-tools';

export {
  GENERATE_MEAL_PLAN_PREVIEW,
  APPLY_MEAL_PLAN,
} from './tools/meal-tools';

export {
  SET_ACTIVE_PURPOSE,
  CLEAR_ACTIVE_PURPOSE,
} from './tools/purpose-tools';

import {
  GET_USER_BASIC_INFO,
  GET_USER_MILITARY_INFO,
  GET_USER_BODY_METRICS,
  GET_LATEST_INBODY,
  GET_INBODY_HISTORY,
  GET_FITNESS_PROFILE,
  UPDATE_FITNESS_PROFILE,
  GET_DIETARY_PROFILE,
  UPDATE_DIETARY_PROFILE,
  CALCULATE_DAILY_NEEDS,
  REQUEST_USER_INPUT,
  CONFIRM_PROFILE_DATA,
} from './tools/profile-tools';

import {
  GET_CURRENT_ROUTINE,
  ADD_EXERCISE_TO_WORKOUT,
  REMOVE_EXERCISE_FROM_WORKOUT,
  REORDER_WORKOUT_EXERCISES,
  UPDATE_EXERCISE_SETS,
  SAVE_ROUTINE_DRAFT,
  GENERATE_ROUTINE_PREVIEW,
  APPLY_ROUTINE,
} from './tools/routine-tools';

import {
  GENERATE_MEAL_PLAN_PREVIEW,
  APPLY_MEAL_PLAN,
} from './tools/meal-tools';

import {
  SET_ACTIVE_PURPOSE,
  CLEAR_ACTIVE_PURPOSE,
} from './tools/purpose-tools';

export const AI_TRAINER_TOOLS: AIToolDefinition[] = [
  GET_USER_BASIC_INFO,
  GET_USER_MILITARY_INFO,
  GET_USER_BODY_METRICS,
  GET_LATEST_INBODY,
  GET_INBODY_HISTORY,
  GET_FITNESS_PROFILE,
  UPDATE_FITNESS_PROFILE,
  GET_DIETARY_PROFILE,
  UPDATE_DIETARY_PROFILE,
  CALCULATE_DAILY_NEEDS,
  GET_CURRENT_ROUTINE,
  SAVE_ROUTINE_DRAFT,
  ADD_EXERCISE_TO_WORKOUT,
  REMOVE_EXERCISE_FROM_WORKOUT,
  REORDER_WORKOUT_EXERCISES,
  UPDATE_EXERCISE_SETS,
  REQUEST_USER_INPUT,
  CONFIRM_PROFILE_DATA,
  GENERATE_ROUTINE_PREVIEW,
  APPLY_ROUTINE,
  GENERATE_MEAL_PLAN_PREVIEW,
  APPLY_MEAL_PLAN,
  SET_ACTIVE_PURPOSE,
  CLEAR_ACTIVE_PURPOSE,
];

export function getToolDefinition(name: AIToolName): AIToolDefinition | undefined {
  return AI_TRAINER_TOOLS.find((tool) => tool.name === name);
}
